# Generated by Django 5.2.8 on 2025-11-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_photo_userconfirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconfirmation',
            name='expiration_date',
        ),
        migrations.AddField(
            model_name='userconfirmation',
            name='expiration_time',
            field=models.DateTimeField(null=True),
        ),
    ]
