# Generated by Django 5.2.8 on 2025-11-28 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userconfirmation_expiration_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userconfirmation',
            old_name='verify_typy',
            new_name='verify_type',
        ),
    ]
