# Generated by Django 5.2.8 on 2025-11-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_verify_typy_userconfirmation_verify_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfirmation',
            name='code',
            field=models.CharField(max_length=9),
        ),
    ]
